language: node_js
node_js:
  - 14
cache:
  directories:
    - ./node-modules

install:
  - npm install

script:
  - npm run-script build
  - cd dist/kms_01
  - cp index.html 404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/kms_01
  on:
    branch: main
